Security Log
skyvers/skyve pull request #128
Opened 2024-08-08 07:38 UTC by simeonbizhub

[Trello](https://trello.com/c/EVsMrsQb)

These changes introduce a new SecurityLog document in the admin module, similar to Audit.
A SecurityLog instance is created in the constructor of `SecurityException`, when `AccessException` or `SecurityException` are thrown.
In order to accomodate these changes, there was some re-jigging required to manage dependencies.

**Re-jigging**
- Removed `HttpServletRequest` & `HttpServletResponse` from `WebContext`
- Added `HttpServletRequestResponse` 
- Added `WebContainer` class to set/get `HttpServletRequestResponse`
- Moved `User.checkAccess` to `EXT` method
- Moved `AccessException`, `SecurityException` from skyve-core to skyve-ext
- Made `HttpServletRequestResponse` injectable via `SkyveCDIProducer`
- Added `getHttpServletRequestResponse` to `EXT`

**Changes**
- Added `SecurityLog` document to admin module
- Update to `RequestLoggingAndStatisticsFilter` to set request/response (cleared in try-finally)
- Added `SecurityLog` interface in skyve-core (`admin.SecurityLog` implements)
- Implemented `SecurityException.log`
- Implemented `SecurityException.email`
- Added `SecurityUtil`
- Added `RecentSecurityLogModel` to `SystemDashboard`

2024-08-13 04:00 UTC, sandsm requested changes
Nice work @simeonbizhub.
Comments to address enclosed.
Some of them are genuine questions coz I dont have the benefit of the compiler during review, so they are just hunch - ignore if I'm wrong.

2024-08-13 04:00 UTC, sandsm commented on skyve-core/src/main/java/org/skyve/domain/app/admin/SecurityLog.java
> +			return CORE.getUser()
3 Calls to CORE.getUser() here, 2 to getCustomer()

2024-08-13 04:00 UTC, sandsm commented on skyve-core/src/main/java/org/skyve/domain/app/admin/SecurityLog.java
> +		} catch (RuntimeException e) {
Do we need to catch Exceptions here? Only throw if you need to, probs chain with a description no matter if its runtime or not - ie ("Could not instantiate a new SecurityLog", e)

2024-08-13 04:00 UTC, sandsm commented on skyve-ext/src/main/java/org/skyve/EXT.java
> +	public static HttpServletRequestResponse getHttpServletRequestResponse() {
Add @Nullable on return type

2024-08-13 04:00 UTC, sandsm commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +		String eventType = exception.getClass()
Maybe a comment for what this is doing?

2024-08-13 04:00 UTC, sandsm commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +	private static void log(@Nonnull String eventType, @Nonnull String eventMessage, Exception exception) {
Is Exception @Nonnull?

2024-08-13 04:00 UTC, sandsm commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +				try {
Do you think its appropriate to chain these exceptions?

2024-08-13 04:00 UTC, sandsm commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +		if ("localhost".equals(UtilImpl.SMTP)) {
Are you sure we should be checking for localhost?
It is feasible there is a setup on a VPS which has a linux mail server running.

2024-08-13 04:00 UTC, sandsm commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +	public static String getSourceIpAddress(HttpServletRequest request) {
There is also a standard "Forwarded" header to inspect - Maybe this method should go in WebUtil.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
Prefer the standard one before looking for the X-Forwarded-... stuff

2024-08-13 04:00 UTC, sandsm commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +		return new StringTokenizer(xForwardedForHeader, ",").nextToken()
nextToken could throw - guard that or use asIterator().

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/ReportDesign/actions/Preview.java
> +		HttpServletRequest request = EXT.getHttpServletRequestResponse()
Potential null problems?

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SecurityLog/SecurityLog.xml
> +	name="SecurityLog"
Name element first?

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/generated/java/modules/admin/domain/SecurityLog.java
> +	private Long threadID;
Investigate using the Srting thread identifier used in wildfly to easily marry up the log with the security exception?

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SecurityLog/SecurityLog.xml
> +		<memo name="eventMessage" required="true">
This is text indexed by default - should it be?

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SecurityLog/SecurityLog.xml
> +		<memo name="provenance">
This is text indexed by default - should it be

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SecurityLog/views/edit.xml
> +	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="edit"
name and title elements first.

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SecurityLog/views/edit.xml
> +	<form border="true" borderTitle="Security Log Details" disabled="true">
indentation looks wrong here

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SecurityLog/views/edit.xml
> +	<actions>
indentation looks wrong here

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SelfRegistration/actions/Register.java
> +		HttpServletRequest request = EXT.getHttpServletRequestResponse()
Potential Null problem possible?

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SelfRegistrationActivation/SelfRegistrationActivationBizlet.java
> +			HttpServletRequest request = EXT.getHttpServletRequestResponse()
NPE?

2024-08-13 04:00 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SystemDashboard/models/RecentSecurityLogModel.java
> +package modules.admin.SystemDashboard.models;
Is the only reason this model exists to show 5?

2024-08-13 23:06 UTC, simeonbizhub commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +	private static void log(@Nonnull String eventType, @Nonnull String eventMessage, Exception exception) {
I have changed this parameter to `@Nullable String provenance`, as this is all that parameter is used for here.

2024-08-13 23:24 UTC, simeonbizhub commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +				try {
My approach to this section of code was to try assure that each part of the process (upsert, email, commit, close etc.) run independently of each other. For example, if the SecurityLog save fails, an email can still be sent with its contents.

I am not throwing any of these exceptions, just logging.  I don't think any of these exceptions can chain, as each piece of code _can_ be run independently - am I missing something or misinterpreting?

2024-08-13 23:26 UTC, simeonbizhub commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +		if ("localhost".equals(UtilImpl.SMTP)) {
Good point - I just copied the code from `ConfigurationExtension.validSMTPHost` here.

Is there a better way for me to check that a valid email has been configured before sending?

2024-08-13 23:42 UTC, simeonbizhub commented on skyve-ext/src/main/java/org/skyve/util/SecurityUtil.java
> +	public static String getSourceIpAddress(HttpServletRequest request) {
Updated to check "Forwarded" header first.

Would be good in WebUtil, but SecurityUtil would not have access to it there as we are in skyve-ext.

2024-08-14 00:11 UTC, simeonbizhub commented on skyve-war/src/main/java/modules/admin/SystemDashboard/models/RecentSecurityLogModel.java
> +package modules.admin.SystemDashboard.models;
Yes - is there a simpler way to achieve this without creating a model? 
Or are there more customisations you would like here?

2024-08-14 00:23 UTC, simeonbizhub commented on skyve-war/src/generated/java/modules/admin/domain/SecurityLog.java
> +	private Long threadID;
I added 'Thread Name' attribute to SecurityLog - `Thread.currentThread.getName`.
Is this what you mean?

2024-08-21 22:38 UTC, sandsm commented on skyve-war/src/main/java/modules/admin/SystemDashboard/models/RecentSecurityLogModel.java
> +package modules.admin.SystemDashboard.models;
I guess maybe a collection and data grid for 5 but the benefits of the model is that it is lazy loaded outside the request response and only loaded on tab change (in SC) so its a better technical solution.

2024-08-21 22:38 UTC, sandsm approved these changes

2024-08-21 22:39 UTC, merged