Simple import export problems
skyvers/skyve pull request #146
Opened 2024-11-06 05:55 UTC by Malcolm-G-Biz

[Trello Card](https://trello.com/c/otY3c0YA)

2024-11-06 06:12 UTC, Malcolm-G-Biz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Simple Import/Export problems in Skyve 9](https://trello.com/c/otY3c0YA/58-simple-import-export-problems-in-skyve-9)

2024-11-15 21:59 UTC, benpetito requested changes

2024-11-15 21:59 UTC, benpetito commented on skyve-war/src/main/java/modules/admin/ImportExportColumn/ImportExportColumnBizlet.java
> +				Customer customer = user.getCustomer();
These lines are redundant now, this can just be written as 

```java
Customer customer = CORE.getCustomer();
```

2024-11-15 21:59 UTC, benpetito commented on skyve-war/src/main/java/modules/admin/ImportExport/ImportExportBizlet.java
> +		}
This has a compilation error, did you generate domain?

2024-11-20 01:15 UTC, merged