add option to flag records that failed to Save in Data Refresh
skyvers/skyve pull request #52
Opened 2022-08-02 01:00 UTC by brandon-klar

2022-08-08 06:28 UTC, brandon-klar commented
https://trello.com/c/Mdz7pZkI/15-add-an-option-to-data-refresh-to-flag-records-that-fail-on-save

2022-08-15 00:18 UTC, benpetito requested changes
Hi @brandon-klar , can you please see my comment on RefreshDocumentTuplesJob and address that?

2022-08-15 00:18 UTC, benpetito commented on skyve-ejb/src/main/java/modules/admin/DataMaintenance/RefreshDocumentTuplesJob.java
> +						if (flagFailedData) {
Hi @brandon-klar, you should not perform a boolean operation on a Boolean object. This should be `if(Boolean.TRUE.equals(flagFailedData)) {`. Can you please update it?

2022-08-15 02:53 UTC, brandon-klar commented
@benpetito - RefreshDocumentTuplesJob has been updated with if (Boolean.TRUE.equals(flagFailedData))

2022-08-15 05:18 UTC, benpetito approved these changes

2022-08-15 05:18 UTC, merged